python main.py \
  --pretrained_model "mistralai/Mistral-7B-Instruct-v0.3" \
  --config_path "config.json" \
  --output_dir "mistral_out" \
  --dataset_text_field="text" \
  --max_steps=1000 \
  --gradient_checkpointing=True \
  --logging_steps=10 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --per_device_train_batch_size "8" \
  --learning_rate 2e-4 \
  --logging_dir 'logs' \
  --max_seq_length 512 \
  --bf16 True \
  --save_steps 500 \
  --lr_scheduler_type cosine \
  --packing True \
  --model_output_path "mistral_checkpoint"
